# -*- coding: utf-8 -*-
"""Tarea 9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sM_iV5WzkP5F50vRlF0N6r90Zyu2Qtuk
"""

'''
Tarea:        Tarea 9
Ejercicios:         Eliminando Valores Duplicados

Autor:        Mariana Mocan
Fecha:        2025-05-30
'''

lista = input("Ingresa una lista de números(num1 -espacio- num2...): ")
lst = []
final = []

for num in lista.split( ):
  lst.append(int(num))

for i in lst:
  if i not in final:
    final.append(i)


print(final)
