# -*- coding: utf-8 -*-
"""Tarea11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18UyqZfAh-HMg6O5kFcngv40FaFAdeESL
"""

'''
Tarea:        Tarea 11
Ejercicios:         Diagonal principal y secundaria

Autor:        Mariana Mocan
Fecha:        2025-06-10
'''

l = [[1,2,3,4], [5,6,7,8] ,[9,10,11,12], [13,14,15,16]]

diagonal_principal = []
diagonal_secundaria = []

for i in range(len(l)):
  for j in range(len(l[i])):
    #print(f"valor en la posición ({i}, {j}): {[i][j]}")

    if i == j:
      diagonal_principal.append(l[i][j])

    if i + j== len(l)-1:
      #print(f"valor en la posición ({i}, {j}): {[i][j]}")
      diagonal_secundaria.append(l[i][j])

print(diagonal_principal)
print(diagonal_secundaria)

'''
Tarea:        Tarea 11
Ejercicios:         Matriz simétrica

Autor:        Mariana Mocan
Fecha:        2025-06-13
'''
N = int(input("Escribe el número de líneas: "))

matriz = []

for i in range(N):
    linea = input(f"Fila {i+1} (nums separados por ,): ")
    fila = list(map(int, linea.split(',')))
    matriz.append(fila)

print("Matriz:")
for fila in matriz:
    print(fila)

'''
Tarea:        Tarea 11
Ejercicios:         Juego del entorno

Autor:        Mariana Mocan
Fecha:        2025-06-14
'''