# -*- coding: utf-8 -*-
"""Num_Lideres.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KgN86GcFXv8wB1PJbEVotsjwams1f3eV
"""

'''
Tarea:        Tarea 9
Ejercicios:         Números Líderes

Autor:        Mariana Mocan
Fecha:        2025-05-30
'''
lista = []
newlista = input("Ingrese numeros (separados por espacio): ")
for i in newlista.split():
  es_lider = True
  for j in newlista.split()[newlista.split().index(i)+1:]:
    if int(i) <= int(j):
      es_lider = False
      break
  if es_lider:
    lista.append(i)
print(lista)