# -*- coding: utf-8 -*-
"""Tarea 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JbgunBlGXIpZmFvpp0nnAMvGoPEIjDpX
"""

'''
Tarea:        Tarea 8
Ejercicio:         Adivina el Número

Autor:        Mariana Mocan
Fecha:        2025-05-30
'''

import random
numero_secreto = random.randint(1, 100)

while True:
  intento = int(input("Adivina el número (entre 1 y 100): "))

  if intento == numero_secreto:
    print("Felicidades! Has adivinado el número secreto")
    break
  elif intento < numero_secreto:
      print("El número secreto es mayor")
  else:
      print("El número secreto es menor")

'''
Tarea:        Tarea 8
Ejercicio:         Sumador de Valores posicionales

Autor:        Mariana Mocan
Fecha:        2025-05-30
'''

numero = input("Ingresa un número de varios dígitos: ")

while len(numero) > 1:
    suma = 0
    for digito in numero:
        suma += int(digito)
    numero = str(suma)

print("El resultado final es:", numero)